baseURL: "https://example.org"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile

Paginate: 6
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
#     - identifier: blog
#       name: Blog
#       title: Blog posts
#       url: /blogs
#       weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 2
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "My profile"
  description: Get to know a bit of my story
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/LogoLaB.png"

  theme:
    disableThemeToggle: false
    defaultTheme: "dark" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/images/LogoLaB.png" # Logo for the brand | default is the favicon variable
    brandName: "Laboratorian" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi,welcome"
    title: " I'm Lorena"
    subtitle: "Front-end developer"
    content: "I am a woman with great initiative, I like to learn constantly, that's why I am an entrepreneur, I want to help companies continue to grow and learn in the process."

    image: /images/lorePhoto1.jpg
    button:
      enable: true
      name: "Resume"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/LorenaRuiz0717
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/lorenruiz/
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/Lore1.jpg"
    content: |-
      Front-End Developer, with knowledge in hotel management, my experience has allowed me to have a focus on the user, discover and solve their needs. Here are some of the technologies I have worked with 
    skills:
      enable: true
      title: "Aquí hay algunas tecnologías con las que he estado trabajando recientemente:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Hugo"
        - "Boostrap Studio"
        - "Penpot"

  # Experience
  experience:
    enable: true
    items:
      - job: "Junior Front end developer"
        company: "Jamgo Tech"
        companyUrl: "https://example.com"
        date: "Oct 2021 - Current"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: |
         I am currently working as  Junior Front end developer at Jamgo Tech in Amsterdam, Holanda. I am learn about JamStack and how use this tecnology for create page of easy maintainability and update of content.

      - job: "Owner Entrepreneurship "
        company: "Happy Pets Art"
        companyUrl: "https://www.facebook.com/Happypetsart"
        date: "Jul 2015 - Current"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          content: Owner Entrepreneurship, accessories and furniture for pets 
        content: |
         Family business, dedicated to the design and handmade of personalized products for pets, focused on comfort and durability.
         This experience has allowed me to develop different skills such as market research and market opening, creation, design, negotiation with direct customers always satisfying, meeting and exceeding their expectations.

      - job: "Service and Kitchen Manager"
        company: "Grupo 5G-La Jugueteria"
        companyUrl: "http://www.restaurantelajugueteria.com.co/"
        date: "March 2015 - April 2020 "
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          # content: I worked as a software developer for more than one year in Amazon.
        content: |
         Restaurant La Juguetería, in charge of the operation, I had the opportunity to lead and train large groups developing a skill in personnel management, service standardisation and customer service. I learned the importance and management of budgets always dynamically and proactively optimising processes day by day. In this company I had a personal and professional growth that allowed me to have different positions and experiences, promoted by my learning and leadership skills.

      - job: "Customer Service Manager"
        company: "Andres Carne de Res"
        companyUrl: "http://www.andrescarnederes.com/"
        date: "Feb 2014 - Nov 2014"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
         In charge of operational staff in different areas supervising a good operational development, taking care of the corporate image. I had the opportunity to learn to lead groups of different ages and social characteristics, which helped me to create a good working environment and strengthen work teams, which was reflected in optimising the service and rotation of diners, surpassing the goals set.

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Front-end Developer "
        school: 
          name: "Laboratoria"
          url: "https://www.laboratoria.la/"
        date: "2021"
        # GPA: "3.8 out of 5.0"
        content: |-
         Unique Bootcamp experience in web development. 
         Based on autonomous learning, carrying out projects under the Agile-Scrum methodology, with learning objectives that simulate a work environment.
      - title: "Diploma in Gastronomic Establishment Management"
        school:
          name: "Escuela de gastronomia Mariano Moreno"
          url: "https://ismm.edu.co/"
        date: "2020"
        # GPA: "3.9 out of 5.0"
        content: |-
         Education focused on the administrative management of gastronomic establishments, with learning achievements such as budget management, inventory costing, recipe standardisation, management and more.
         It allowed me to understand the importance of high quality and meeting expectations.
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"
      - title: "Hotel Management Technologist"
        school:
          name: "SENA"
          url: "http://senahoteleriaturismoalimentos.blogspot.com/"
        date: "2011"
        # GPA: "4.2 out of 5.0"
        content: |-
         Educational, theoretical and practical process in the administrative and operational area of gastronomic and tourist establishments. Internship at the Hotel JW Marriot Bogotá, where I had a personal and professional growth in the area of restaurants, I met and learned about service, high level gastronomy and the importance of experiences.
        featuredLink:
          enable: false
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    items:
      - title: Talent Fest Colombia 2021 | People's Choice
        image: /images/PeopleChoice.png
        # content: People's Choice
        url: https://www.credential.net/eaf9a290-e7e9-4078-acb7-18957feb8d28
      - title:  Talent Fest Colombia 2021 |  2do Puesto
        image: /images/2puesto talentFest.png
        # content:  2do Puesto
        url: https://www.credential.net/8b944c7d-5fa8-4d32-bc02-a72488a499d2
      - title: Scrum Fundamental | Soy Líder.Net
        image: /images/ScrumStudy.png
        # content: We are developed a product which can help others.
        url: https://c46e136a583f7e334124-ac22991740ab4ff17e21daf2ed577041.ssl.cf1.rackcdn.com/Certificate/ScrumFundamentalsCertified-PaulaLorenaRuizDiaz.-860667.pdf
      # - title: Google Summer of Code
      #   content: Contributed to a open source project.
      #   url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Pet Book 
        content: Social network focused on Pet Lovers. Making use of Firebase, Firestore, based on SPA method. Responsive Design 
        image: /images/projects/PetBook.png
        featured:
          name: Demo
          link: https://gloriacuba.github.io/BOG002-social-network/src/index.html
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/LorenaRuiz0717/BOG002-social-network

      - title:  Data Lovers
        content: Interface that organises and filters data according to different characteristics, Responsive Design, built in vanilla JavaScript.
        image: /images/projects/DataLovers.png
        featured:
          name: Demo
          link: https://paolacm99.github.io/BOG002-data-lovers/
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/LorenaRuiz0717/BOG002-data-lovers
        #   - icon: fa fa-envelope
        #     url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/hugo-profile
        #   - icon: fab fa-twitter
        #     url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

 
      - title: Card Validation
        content: Interface in online shop context, validation for credit card number, implemented in vanilla JavaScript.
        image: /images/projects/cardValidation.png
        # featured:
        #   name: Code
        #   link: https://github.com/LorenaRuiz0717/BOG002-card-validation
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url:  https://github.com/LorenaRuiz0717/BOG002-card-validation

      # - title: Card Validation
      #   content: Interface in online shop context, validation for credit card number, implemented in vanilla JavaScript.
      #   image: /images/projects/cardValidation.png
        # featured:
        #   name: Code
        #   link: https://github.com/LorenaRuiz0717/BOG002-card-validation
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        # links:
        #   - icon: fab fa-github
        #     url:  https://github.com/LorenaRuiz0717/BOG002-card-validation


  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi! 
    email: lorena0717@hotmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/LorenaRuiz0717
      linkedin: https://www.linkedin.com/in/lorenruiz/
      # instagram: https://instagram.com
      # facebook: https://facebook.com
