baseURL: "https://lorenaruiz0717.github.io/profile/"
languageCode: "en-us"
title: "Lorena Ruiz-Desarrolladora Fron-end"
theme: hugo-profile

Paginate: 6
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
#     - identifier: blog
#       name: Blog
#       title: Blog posts
#       url: /blogs
#       weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 2
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Mi perfil"
  description: Conoce un poco de mi historia
  # staticPath: ""  # The path to serve the static files from
  favicon: "images/LogoLaB.png"

  theme:
    disableThemeToggle: false
    defaultTheme: "dark" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "images/LogoLaB.png" # Logo for the brand | default is the favicon variable
    brandName: "Laboratorian" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hola,bienvenido"
    title: " Soy Lorena"
    subtitle: "Junior Front-end"
    content: "Soy una mujer con gran iniciativa, me gusta estar en constante aprendizaje, por eso soy emprendedora, quiero ayudar a las empresas a seguir creciendo y aprender en el proceso."

    image: images/lorePhoto1.jpg
    # button:
    #   enable: true
    #   name: "Resume"
    #   url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/LorenaRuiz0717
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/lorenruiz/
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "Sobre mi"
    image: "images/Lore1.jpg"
    content: |-
     Desarrolladora Front-End, con conocimientos en administración Gastronómica y  hotelera, mi experiencia me ha permitido tener un enfoque en el usuario, descubrir y resolver sus necesidades.
    skills:
      enable: true
      title: "Estas son algunas de las tecnologías con las que he trabajado recientemente:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Hugo"
        - "Boostrap Studio"
        - "Penpot"

  # Experience
  experience:
    enable: true
    items:
      - job: "Junior Front end developer"
        company: "Jamgo Tech"
        # companyUrl: "https://example.com"
        date: "Octubre 2021 - Abril 2022"
        # featuredLink:
        #   enable: false
        #   name: "View the project"
        #   url: "https://example.com"
        content: |
         Jamgo Tech es un startup ubicado en Amsterdam, Holanda. Tuve la oportunidad de aprender  sobre desarrollo  JamStack y cómo utilizar esta tecnología para crear páginas de fácil mantenimiento y actualización de contenidos. 

      - job: "Emprendimiento personal"
        company: "Happy Pets Art"
        companyUrl: "https://www.facebook.com/Happypetsart"
        date: "Jul 2015 - Abril 2022"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
          content: Owner Entrepreneurship, accessories and furniture for pets 
        content: |
          Emprendimiento familiar, dedicado al diseño y elaboración manual de productos personalizados para mascotas, enfocados en el confort y la durabilidad.Esta experiencia me ha permitido desarrollar diferentes habilidades como la investigación y apertura del mercado, creación, diseño, negociación con los clientes directos siempre satisfaciendo, cumpliendo y superando sus expectativas.
      - job: "Admnistrador de servicio y cocina"
        company: "Grupo 5G-La Jugueteria"
        companyUrl: "http://www.restaurantelajugueteria.com.co/"
        date: " Marzo 2015 - Abril 2020 "
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |
         Restaurante La Juguetería, estuve a cargo de la operación, tuve la oportunidad de liderar y entrenar grandes grupos desarrollando una habilidad en la gestión de personal, estandarización del servicio y atención al cliente. Aprendí la importancia y manejo de los presupuestos siempre de manera dinámica y proactiva optimizando los procesos día a día. En esta empresa tuve un crecimiento personal y profesional que me permitió tener diferentes posiciones y experiencias, promovidas por mi aprendizaje y capacidad de liderazgo.

      - job: "Jefe de servicio al cliente"
        company: "Andres Carne de Res"
        companyUrl: "http://www.andrescarnederes.com/"
        date: "Febrero 2014 - Noviembre 2014"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |
         Estuve a cargo del personal en diferentes áreas supervisando un buen desarrollo operativo, cuidando la imagen corporativa. Tuve la oportunidad de aprender a liderar grupos de diferentes edades y características sociales, lo que me ayudó a crear un buen ambiente de trabajo y a fortalecer los equipos de trabajo, lo que se reflejó en la optimización del servicio y la rotación de los comensales, superando las metas establecidas.

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Front-end Developer "
        school: 
          name: "Laboratoria"
          url: "https://www.laboratoria.la/"
        date: "2021"
        # GPA: "3.8 out of 5.0"
        content: |-
         Experiencia única de Bootcamp en desarrollo web.  Basado en el aprendizaje autónomo, realizando proyectos bajo metodología Agile-Scrum, con objetivos de aprendizaje que simulan un entorno de trabajo.
      - title: "Diplomado en Administración de Establecimientos Gastronomicos"
        school:
          name: "Escuela de Gastronomia Mariano Moreno"
          url: "https://ismm.edu.co/"
        date: "2020"
        # GPA: "3.9 out of 5.0"
        content: |-
         Educación enfocada en el manejo administrativo de establecimientos Gastronómicos, con logros de aprendizaje tales como manejo de presupuestos, costo de inventarios, estandarización de recetas,gestión y mas.Me permitió entender la importancia de la alta calidad y el cumplir expectativas.
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"
      - title: "Tecnologo en Administración Hotelera"
        school:
          name: "SENA"
          url: "http://senahoteleriaturismoalimentos.blogspot.com/"
        date: "2011"
        # GPA: "4.2 out of 5.0"
        content: |-
         Proceso educativo, teórico practico en el área administrativa y operativa de establecimientos gastronómicos y turísticos. Pasantía realizada en el Hotel JW Marriot Bogotá, donde tuve un crecimiento personal y profesional en el área de restaurantes, conocí y aprendí sobre servicio, gastronomía de alto nivel y la importancia de las experiencias.
        featuredLink:
          enable: false
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    items:
      - title: Talent Fest Colombia 2021 | People's Choice
        image: images/PeopleChoice.png
        # content: People's Choice
        url: https://www.credential.net/eaf9a290-e7e9-4078-acb7-18957feb8d28
      - title:  Talent Fest Colombia 2021 |  2do Puesto
        image: images/2puesto talentFest.png
        # content:  2do Puesto
        url: https://www.credential.net/8b944c7d-5fa8-4d32-bc02-a72488a499d2
      - title: Scrum Fundamental | Soy Líder.Net
        image: images/ScrumStudy.png
        # content: We are developed a product which can help others.
        url: https://c46e136a583f7e334124-ac22991740ab4ff17e21daf2ed577041.ssl.cf1.rackcdn.com/Certificate/ScrumFundamentalsCertified-PaulaLorenaRuizDiaz.-860667.pdf
      # - title: Google Summer of Code
      #   content: Contributed to a open source project.
      #   url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Pet Book 
        content: Red social enfocada en Pet Lovers. Haciendo uso de Firebase, Firestore, planteada en metodo SPA. Diseño Responsive
        image: images/projects/PetBook.png
        featured:
          name: Demo
          link: https://gloriacuba.github.io/BOG002-social-network/src/index.html
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/LorenaRuiz0717/BOG002-social-network

      - title:  Data Lovers
        content: Interfaz que organiza y filtra datos según diferentes características , Diseño Responsive, planteada en vanilla JavaScript.
        image: images/projects/DataLovers.png
        featured:
          name: Demo
          link: https://paolacm99.github.io/BOG002-data-lovers/
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/LorenaRuiz0717/BOG002-data-lovers
        #   - icon: fa fa-envelope
        #     url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/hugo-profile
        #   - icon: fab fa-twitter
        #     url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

 
      - title: Card Validation
        content: Interfaz en contexto tienda virtual, validación para número de tarjeta crédito, planteada en vanilla JavaScript.
        image: images/projects/cardValidation1.png
        featured:
          name: Demo
          link: https://lorenaruiz0717.github.io/Vs0.2-CardValidation-BOG002/src/index.html
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url:  https://github.com/LorenaRuiz0717/Vs0.2-CardValidation-BOG002

      # - title: Card Validation
      #   content: Interface in online shop context, validation for credit card number, implemented in vanilla JavaScript.
      #   image: /images/projects/cardValidation.png
        # featured:
        #   name: Code
        #   link: https://github.com/LorenaRuiz0717/BOG002-card-validation
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        # links:
        #   - icon: fab fa-github
        #     url:  https://github.com/LorenaRuiz0717/BOG002-card-validation


  #Contact
  contact:
    enable: true
    content: My correo siempre esta abierto, para una pregunta o un saludo .Gracias por visitar mi perfil   
    email: lorena0717@hotmail.com
    btnName: E-mail

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/LorenaRuiz0717
      linkedin: https://www.linkedin.com/in/lorenruiz/
      # instagram: https://instagram.com
      # facebook: https://facebook.com
